### ISSUE TITLE
[loire] Battery drain

### ISSUE THREAD

**Issue by Gray47Maxx** [RiseOS/bug_tracker#15]
**Device:** Suzu
**Kernel version:** 4.9.103
**Android version:** 9 (Omni)

**Description:**
The result of not-so-good optimized kernel, the battery drainage is surprisingly big. Also, looks like the drainage is big even in sleep mode.

**How to reproduce:**
Install a system and use it for one day. Then compare the results with 4.4 Oreo or 3.10 stock.

**Logs:**
Can provide if needed.

**Comment by danielgusvt** [comment]
@Gray47Maxx provide screenshots from betterbatterystats

**Comment by Gray47Maxx** [comment]
Will do that once I'll get ROS running on my device

**Comment by Gray47Maxx** [comment]
Fixed with v5 blobs
