### ISSUE TITLE
[loire] broken audio

### ISSUE THREAD

**Issue by bartcubbins** [RiseOS/bug_tracker#17]
**Device:** suzu
**Kernel version:** 4.9.x
**Android version:** 9.0.0_r16

**Description:**
no audio

**How to reproduce:**
...

**Logs:**
dmesg
https://gist.github.com/bartcubbins/c2ff215f39fe2b3ed5d3f8444bcec83b
logcat
https://gist.github.com/bartcubbins/69818748659a873209ff6b375563b4f0

**Comment by bartcubbins** [comment]
@Gray47Maxx do you have audio on omni build?

**Comment by Gray47Maxx** [comment]
Do you have no audio everywhere or just while calling to someone?

**Comment by bartcubbins** [comment]
@Gray47Maxx only audio/vorbis is broken.
Reason:
https://github.com/RiseOS/device_sony_common/commit/81aa32f2675b20acddcda3be84534e4758c56d93

**Comment by bartcubbins** [comment]
https://github.com/RiseOS/device_sony_common/commit/c5e33d4a3b83728993afb89493e94bbd37b6528e
https://github.com/RiseOS/platform_external_tinycompress/commit/46eaab1a45f5a45d27ddbe0693c7016549374a1b
