### ISSUE TITLE
[loire] (ex/v)FAT SD cards are not readable by system

### ISSUE THREAD

**Issue by Gray47Maxx** [RiseOS/bug_tracker#19]
**Device: suzu (F5121)** 
**Kernel version: 4.9** 
**Android version: 9.0.0 (ROS)** 

**Description:**
exFAT/vfat SD cards can't be read by system. Formatting helps, but for a short period of time. May be related to [this](https://github.com/sonyxperiadev/bug_tracker/issues/163) and [this](https://github.com/sonyxperiadev/bug_tracker/issues/102).

**How to reproduce:**
Try to use any exFAT/vfat SD card.

**Logs:**
Will provide soon.

**Comment by danielgusvt** [comment]
Nah it's not related to what you've linked
Please run these commands on a fresh boot
```
dmesg | grep -i fat
adb logcat -v brief vold:V *:S
ls /system/bin/mkfs.exfat
ls /system/bin/fsck.exfat
```

**Comment by bartcubbins** [comment]
@danielgusvt *.exfat is missing, check our repos:)
