### ISSUE TITLE
[Suzu] Quick Charge 2.0

### ISSUE THREAD

**Issue by lubik1** [RiseOS/bug_tracker#21]
**Device:** Suzu
**Kernel version:** 4.9.138 
**Android version:** 9

**Description:**
Our platform and device support QC 2.0 as on Stock FW, but it doesn't work on Rise OS

**How to reproduce:**
Turn device to QC 2.0 or 3.0 charger and it disconnect it (software) and doesn't want charge with even low (standart mode)

**Comment by bartcubbins** [comment]
fixed
https://github.com/bartcubbins/kernel_loire/commit/2b5fdc84600620e8ae146a7c888f7c9ebfbe397d
