### ISSUE TITLE
[Suzu] Incall sound

### ISSUE THREAD

**Issue by lubik1** [RiseOS/bug_tracker#22]
**Device:** Suzu
**Kernel version:** 4.9.138
**Android version:** 9

**Description:**
Then you call someone, you don't hear anything except "bip" then call is end

**How to reproduce:**
Just call someone

**Logs:**
if it help:
[1.log](https://github.com/RiseOS/bug_tracker/files/2636874/1.log)

**Comment by bartcubbins** [comment]
the same issue with k4.4

**Comment by bartcubbins** [comment]
blobs issue

**Comment by bartcubbins** [comment]
Fixed
