### ISSUE TITLE
[suzu] Can't download files using default download manager 

### ISSUE THREAD

**Issue by Gray47Maxx** [RiseOS/bug_tracker#25]
**Device:** suzu
**Kernel version:** 4.9.144
**Android version:** 9

**Description:**
Can't download files through the browser. The progress of download didn't showing up in the statusbar, but after some time and if you turn the display off, it says "can't download file".

Tried to load a file from 4PDA app, isn't working either. 

Downloading thru Telegram X app works.

**How to reproduce:**
Try to download anything.

**Logs:**
Can provide if needed.

**Comment by bartcubbins** [comment]
I can download files using chromium or 4pda app. I just can not download files from gdrive

**Comment by bartcubbins** [comment]
can't reproduce this issue
