### ISSUE TITLE
EXFAT

### ISSUE THREAD

**Issue by Gray47Maxx** [RiseOS/bug_tracker#3]
**Device:** Xperia M4 Aqua
**Kernel version:** 3.10.xx
**Android version:** 8.1.0

**Description:**
Looks like we don't have exfat support or it's partially broken.

**How to reproduce:**
Try to use MicroSD formatted to EXFAT...

**Comment by danielgusvt** [comment]
Solution:
Enable these
PRODUCT_PACKAGES += \
    libfuse \
    fsck.exfat \
    mkfs.exfat \
    mount.exfat

**Comment by bartcubbins** [comment]
exfat fixed
