### ISSUE TITLE
CYTTSP5 Touchscreen

### ISSUE THREAD

**Issue by Gray47Maxx** [RiseOS/bug_tracker#5]
**Device:** Xperia M4 Aqua
**Kernel version:** 3.10.xx
**Android version:** 8.1.0

**Description:**
**Maybe** the cyttsp5 touchscreen is broken, fully or partionally.

**How to reproduce:**
Check the logs.

**Comment by bartcubbins** [comment]
fixed at this point
https://github.com/bartcubbins/kernel_kanuti/commit/7bc790f72e91c27fb91cfb3c86e792e5a8cc2dd3
